### ISSUE TITLE
direc.replace somewhere

### ISSUE THREAD

**Issue by MarcoVando** [msujas/maskGenerator_CdTe#1]
Hi kenneth
I was running the code and I got this error.
I installed the package as u mentioned with pip install -e .
I then run imagin from the same folder

(I replaced the actual path with "..." in the lines below)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/marco/.../pdf/303K_vac_activated/xrd/Z:/visitor/ch6985/bm31/20240610/pylatus/pilatusPixelCorrections.h5'
Unable to configure detector NexusDetector with config: {}

[Errno 2] No such file or directory: '/Users/marco/.../pdf/303K_vac_activated/xrd/Z:/visitor/ch6985/bm31/20240610/pylatus/pilatusPixelCorrections.h5

I think there's a direc.replace somewhere in ur files.

**Comment by msujas** [comment]
It's probably your MD.poni file. You need to change the path to the module distortion file in there (pilatusPixelCorrections.h5). Otherwise I'll have a look tomorrow.
